# Auto-generated by agent-shim's release workflow on every tagged release — do not edit manually.
class AgentShim < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/agent-shim"
  version "8.33.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.33.0/agent-shim-macos-arm64"
      sha256 "c4b148dfd83c08c679584dc04eae58688dabeaf427889b27c7ba0d14a88847d9"
    end
    on_intel do
      # The SEA binary segfaults on every invocation on real x64 macOS hardware -- a known, unfixed upstream Node bug (see docs/release-process.md's "Build (Node SEA)" section for the full writeup and citations). Installs via npm + a Homebrew-managed Node instead, same code this project already publishes and verifies on the npm channel, on every other platform.
      url "https://registry.npmjs.org/agent-shim/-/agent-shim-8.33.0.tgz"
      sha256 "521058d2420e45637402a970819237771816593ba6f518c4d1348db7df9adfd8"
      depends_on "node"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.33.0/agent-shim-linux-arm64"
      sha256 "60531a36bf4098861216ac2c7575ac1a54bc08947ba9509ef7ed46c01c797a66"
    end
    on_intel do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.33.0/agent-shim-linux-x64"
      sha256 "af07162734871ef465944526345cfb6e7bce9a5988143ae46d834488e40a6110"
    end
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      downloaded = Dir["agent-shim-*"].first
      bin.install downloaded => "agent-shim"
      chmod 0755, bin/"agent-shim"
      bin.install_symlink bin/"agent-shim" => "claude-use"
    end
  end

  def caveats
    <<~EOS
      agent-shim is installed alone -- nothing on this system claims the `claude` command by default.
      Run `agent-shim run [args...]` to use the launcher directly, or `agent-shim shim enable` once
      if you'd also like the shorter `claude @<name>` form (`agent-shim shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-shim --version")
  end
end
