# Auto-generated by agent-shim's release workflow on every tagged release — do not edit manually.
class AgentShim < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/agent-shim"
  version "8.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.5.0/agent-shim-macos-arm64"
      sha256 "8968dd0f18355a5310a5a0ddfd27ae21f45811522fbe512c1ba2b25fb048c997"
    end
    on_intel do
      # The SEA binary segfaults on every invocation on real x64 macOS hardware -- a known, unfixed upstream Node bug (see docs/release-process.md's "Build (Node SEA)" section for the full writeup and citations). Installs via npm + a Homebrew-managed Node instead, same code this project already publishes and verifies on the npm channel, on every other platform.
      url "https://registry.npmjs.org/agent-shim/-/agent-shim-8.5.0.tgz"
      sha256 "d81f04af6c6c79bad23eae0046da06f5d22f930932630797e5ae993df53ee0bc"
      depends_on "node"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.5.0/agent-shim-linux-arm64"
      sha256 "6f9e677da83f1fb602890a6c12bb68b132c0d88e891d70bc0861332c8bbbb252"
    end
    on_intel do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.5.0/agent-shim-linux-x64"
      sha256 "1c05e010167441b2c6b2bc357c5247bc83514e7b437dd6c7531295bb6c2e8a4c"
    end
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      downloaded = Dir["agent-shim-*"].first
      bin.install downloaded => "agent-shim"
      chmod 0755, bin/"agent-shim"
      bin.install_symlink bin/"agent-shim" => "claude-use"
    end
  end

  def caveats
    <<~EOS
      agent-shim is installed alone -- nothing on this system claims the `claude` command by default.
      Run `agent-shim run [args...]` to use the launcher directly, or `agent-shim shim enable` once
      if you'd also like the shorter `claude @<name>` form (`agent-shim shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-shim --version")
  end
end
