# Auto-generated by agent-shim's release workflow on every tagged release — do not edit manually.
class AgentShim < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/agent-shim"
  version "8.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.8.0/agent-shim-macos-arm64"
      sha256 "a496c8c7b81e03b4c388929df491b6c43b27fa12efc7596bcd94d29b553e767a"
    end
    on_intel do
      # The SEA binary segfaults on every invocation on real x64 macOS hardware -- a known, unfixed upstream Node bug (see docs/release-process.md's "Build (Node SEA)" section for the full writeup and citations). Installs via npm + a Homebrew-managed Node instead, same code this project already publishes and verifies on the npm channel, on every other platform.
      url "https://registry.npmjs.org/agent-shim/-/agent-shim-8.8.0.tgz"
      sha256 "15c103c7bc649c8a6a03604e3f7df6ca88429d0ccdf45398fe5ef7bf8da96def"
      depends_on "node"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.8.0/agent-shim-linux-arm64"
      sha256 "e2eec0ab7227fd55cfc6d2db75a1e96ad2880949a35385a18798b59343145883"
    end
    on_intel do
      url "https://github.com/ExaDev/agent-shim/releases/download/v8.8.0/agent-shim-linux-x64"
      sha256 "5aed3eb06003d7c7ebc19ebc4c6e92fabc304a382ab7cdfe770e721d094947d6"
    end
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      downloaded = Dir["agent-shim-*"].first
      bin.install downloaded => "agent-shim"
      chmod 0755, bin/"agent-shim"
      bin.install_symlink bin/"agent-shim" => "claude-use"
    end
  end

  def caveats
    <<~EOS
      agent-shim is installed alone -- nothing on this system claims the `claude` command by default.
      Run `agent-shim run [args...]` to use the launcher directly, or `agent-shim shim enable` once
      if you'd also like the shorter `claude @<name>` form (`agent-shim shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-shim --version")
  end
end
