# Auto-generated by claude-use's release workflow on every tagged release — do not edit manually.
class ClaudeUse < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/claude-use"
  version "5.4.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v5.4.0/claude-use-macos-arm64"
      sha256 "68cc17744826db38880597f470fe4ed02013f58b00824b062bef83310cf7d29e"
    end
    on_intel do
      # The SEA binary segfaults on every invocation on real x64 macOS hardware -- a known, unfixed upstream Node bug (see docs/release-process.md's "Build (Node SEA)" section for the full writeup and citations). Installs via npm + a Homebrew-managed Node instead, same code this project already publishes and verifies on the npm channel, on every other platform.
      url "https://registry.npmjs.org/claude-use/-/claude-use-5.4.0.tgz"
      sha256 "0d205677950ca78b427565f32312aac62c5e82bbe617f75c1a0a6d841b2cd4e6"
      depends_on "node"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v5.4.0/claude-use-linux-arm64"
      sha256 "5603ec6c7dd9f772a91bbc2ea153bf69218840f775b1ac1a465f0e98fac03aa8"
    end
    on_intel do
      url "https://github.com/ExaDev/claude-use/releases/download/v5.4.0/claude-use-linux-x64"
      sha256 "394e4bdb0f8c4b510d2ddd1a07a0c5045e4b9b5e0fdbc99dc524f75969c88c99"
    end
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      downloaded = Dir["claude-use-*"].first
      bin.install downloaded => "claude-use"
      chmod 0755, bin/"claude-use"
    end
  end

  def caveats
    <<~EOS
      claude-use is installed alone -- nothing on this system claims the `claude` command by default.
      Run `claude-use run [args...]` to use the launcher directly, or `claude-use shim enable` once
      if you'd also like the shorter `claude @<name>` form (`claude-use shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-use --version")
  end
end
