# Auto-generated by claude-use's release workflow on every tagged release — do not edit manually.
class ClaudeUse < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/claude-use"
  version "2.9.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.9.0/claude-use-macos-arm64"
      sha256 "e8cb279f5dfb2ad5da490268da14292759cb247289640a71dcaa1d0d30afa673"
    end
    on_intel do
      # The SEA binary segfaults on every invocation on real x64 macOS hardware -- a known, unfixed upstream Node bug (see docs/release-process.md's "Build (Node SEA)" section for the full writeup and citations). Installs via npm + a Homebrew-managed Node instead, same code this project already publishes and verifies on the npm channel, on every other platform.
      url "https://registry.npmjs.org/claude-use/-/claude-use-2.9.0.tgz"
      sha256 "ef4359fecc5794af7105adfcdfa15e85d797142c6d6f02a3f553f07d37801cf0"
      depends_on "node"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.9.0/claude-use-linux-arm64"
      sha256 "1cce11994ccfa748d51c8a19aae5b425b17d21a109045009e4d6ffb6c4959d6b"
    end
    on_intel do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.9.0/claude-use-linux-x64"
      sha256 "ac2ffbe3fa44e09187b03169909a5065e4ef740b3d8262c8abe55bfbc6877fb9"
    end
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      downloaded = Dir["claude-use-*"].first
      bin.install downloaded => "claude-use"
      chmod 0755, bin/"claude-use"
    end
  end

  def caveats
    <<~EOS
      claude-use is installed alone -- nothing on this system claims the `claude` command by default.
      Run `claude-use run [args...]` to use the launcher directly, or `claude-use shim enable` once
      if you'd also like the shorter `claude @<name>` form (`claude-use shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-use --version")
  end
end
