# Auto-generated by claude-use's release workflow on every tagged release — do not edit manually.
class ClaudeUse < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/claude-use"
  version "2.8.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.8.0/claude-use-macos-arm64"
      sha256 "b95da87455c6e0b8be554211c228e1055f58090ab9e8052349f8a7565897b811"
    end
    on_intel do
      # The SEA binary segfaults on every invocation on real x64 macOS hardware -- a known, unfixed upstream Node bug (see docs/release-process.md's "Build (Node SEA)" section for the full writeup and citations). Installs via npm + a Homebrew-managed Node instead, same code this project already publishes and verifies on the npm channel, on every other platform.
      url "https://registry.npmjs.org/claude-use/-/claude-use-2.8.0.tgz"
      sha256 "8a74949f11826c9fd7804b4399bd852afcd398d94416efb57682a6cfd9b464c8"
      depends_on "node"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.8.0/claude-use-linux-arm64"
      sha256 "5cb94ce536b5d538ecf31d8f6d18bf879f5563efaba0653d54cf0f84bc5c3c01"
    end
    on_intel do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.8.0/claude-use-linux-x64"
      sha256 "008f1bf6b2afa6d075df2c520c790e2a520ec072e67e8711985288de43cfc150"
    end
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      downloaded = Dir["claude-use-*"].first
      bin.install downloaded => "claude-use"
      chmod 0755, bin/"claude-use"
    end
  end

  def caveats
    <<~EOS
      claude-use is installed alone -- nothing on this system claims the `claude` command by default.
      Run `claude-use run [args...]` to use the launcher directly, or `claude-use shim enable` once
      if you'd also like the shorter `claude @<name>` form (`claude-use shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-use --version")
  end
end
